### ISSUE TITLE
Downloading Metadata Colour

### ISSUE THREAD

**Issue by lunarwolfspirit** [esskayesss/kanagawa-qbtheme#1]
The colour when downloading metadata from magnet links looks nearly identical to the background - could we choose a different shade?

**Comment by esskayesss** [comment]
i wanted to keep the downloading metadata colors pretty muted. you're correct in your observation, but it was intended at the time of making. i've made some changes, though. Brightened the `Downloading` and `Forced Downloading`. I've also changed the `Downloading Metadata` color.

please check the dev branch for the new theme. tell me if you like it. i'll merge it on a positive response. here's a link to the file: https://github.com/esskayesss/kanagawa-qbtheme/blob/dev/kanagawa.qbtheme

**Comment by lunarwolfspirit** [comment]
Looks great now, thanks!

**Comment by esskayesss** [comment]
merged ✅
